typography_spectrum: 0.4304043392185122
color:
  saturation: 0.36231942288577557
  brandStrength: 0.11274218931794167
  lightness: 0.6751728001981974
  brandColors:
    - '#0F1C2C'
    - '#24CBD3'
    - '#002737'
    - '#38C1C6'
    - '#2C808D'
  rhythmicContrast: 0.539275644114241
layout_spectrum: 0.6970916690770537
name: vandepolder
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DESIGN • BRANDING • PHOTOGRAPHY
description: Articles about how to express your brand
