typography_spectrum: 0.1182796
color:
  saturation: 0.9502460935618728
  brandStrength: 0
  lightness: 0.8181378652807325
  brandColors:
    - '#0E1C2C'
    - '#25CBD3'
    - '#17626F'
    - '#113543'
    - '#1C838E'
  rhythmicContrast: 0.07190931309014559
layout_spectrum: 0.2706093
name: vandepolder
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DESIGN • BRANDING • PHOTOGRAPHY
description: Readings about ways to express your brand
